image: ghcr.io/cirruslabs/flutter

variables:
  FLUTTER_VERSION: "3.41.6"

stages:
  - test
  - build

unit_tests:
  stage: test
  image: ghcr.io/cirruslabs/flutter:$FLUTTER_VERSION
  tags:
    - dev
  script:
    - flutter pub get
    - flutter test test/unit/**
  only:
    - master

logic_integration_tests:
  stage: test
  image: ghcr.io/cirruslabs/flutter:$FLUTTER_VERSION
  tags:
    - dev
  script:
    - flutter pub get
    - flutter test test/integration/**
  only:
    - master

build_dev:
  stage: build
  image: ghcr.io/cirruslabs/flutter:$FLUTTER_VERSION
  tags:
    - dev
  script:
    - flutter build apk --release
  artifacts:
    paths:
      - build/app/outputs/flutter-apk/app-release.apk
    expire_in: 1 month
  only:
    - master




#  