default_platform(:ios)

platform :ios do
  desc "Upload build to App Store (new version)"
  lane :release do
    app_store_connect_api_key(
      key_id: ENV["APPSTORE_KEY_ID"],
      issuer_id: ENV["APPSTORE_ISSUER_ID"],
      key_content: ENV["APPSTORE_P8"],
      duration: 1200,
      in_house: false
    )

    # If you already built the IPA with Flutter, just point to it:
    deliver(
      ipa: "build/ios/ipa/*.ipa",
      skip_screenshots: true,
      skip_metadata: true,
      force: true
    )
  end
end
